project:
  type: website
  output-dir: docs

website:
  title: "Ivan Sumaneev"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: code.qmd
        text: Code

format:
  html:
    theme: cosmo
    css: styles.css
    